### ISSUE TITLE
Deploy automatico per testare fuori dall'ambiente di lavoro

### ISSUE THREAD

**Issue by MilanRiccardo03** [EliaBergamin/Progetto-TecWeb#9]
Per non dover ogni volta aprire l'ambiente di lavoro e far partire il docker e soprattutto per testare al meglio da mobile, sarebbe opportuno:
 - [x] creare account altervista per hostare gratuitamente il sito
 - [x] creare account altervista ftp dal pannello altervista con cui vengono forniti http://it.help.altervista.org/w/FTP:
     - Host FTP: di solito è ftp.nome-dominio-altervista.com
     - Nome utente: il tuo nome utente FTP
     - Password: la password che hai scelto
     - Directory: la directory dove vuoi caricare i tuoi file (solitamente /public_html).
- [ ] creare token github: `settings -> secrets and variables -> new repository secret` e aggiungere
     - FTP_HOST: l'host FTP di AlterVista.
     - FTP_USERNAME: il tuo nome utente FTP.
     - FTP_PASSWORD: la tua password FTP.
- [x] creare action per la pubblicazione: nella root del progetto `.github/workflows/deploy.yml` che dovrebbe essere così (da testare)
```
 name: Deploy to AlterVista

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install FTP Client
        run: sudo apt-get install -y lftp

      - name: Upload to AlterVista
        run: |
          lftp -u "$FTP_USERNAME","$FTP_PASSWORD" "$FTP_HOST" <<EOF
          mirror --delete --verbose ./public /public_html
          bye
          EOF
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
```
